name: Java CI with Maven (JaCoCo Diagnostics)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test Java Components

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # Run verify with error output enabled to catch Surefire/Test issues
      - name: Build, Test, and Verify with Maven
        # Use -e to print full stack trace on error
        # Run without the skip profile to attempt the merge
        run: mvn -B verify -e

      # ---- DETAILED DIAGNOSTIC STEP ----
      - name: Check for jacoco.exec files and Test Reports AFTER verify
        if: always() # Run regardless of verify success/failure
        run: |
          echo "--- Detailed check START ---"
          echo ""
          echo ">>> Listing ALL target directories:"
          ls -d */target/ shodrone-backoffice/*/target/ || echo "No target dirs found?"
          echo ""
          echo ">>> Searching for jacoco.exec files:"
          find . -path '*/target/jacoco.exec' -exec ls -l {} \; || echo "No jacoco.exec files found."
          echo ""
          echo ">>> Searching for Surefire XML reports:"
          find . -path '*/target/surefire-reports/*.xml' -exec ls -l {} \; || echo "No Surefire reports found."
          echo ""
          # Optionally, show the content of Surefire reports if few/small
          # find . -path '*/target/surefire-reports/*.xml' -exec echo "Content of {}:" \; -exec cat {} \; -exec echo "" \;
          echo "--- Detailed check END ---"
      # ---- END DIAGNOSTIC STEP ----

      - name: Upload Unit Test Results (Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          # Double-check if reports exist before uploading
          path: |
            **/target/surefire-reports/*.xml
          if-no-files-found: warn # Don't fail the workflow if reports are missing, just warn

      - name: Upload Code Coverage Report (Jacoco Aggregate)
        if: success() # Only upload if verify succeeded (meaning merge/report worked)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-aggregate-report
          path: shodrone-util-ci/target/site/jacoco-aggregate/
          if-no-files-found: fail # Fail if the report wasn't generated on success