name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test Java Components

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # *** Run standard verify without skipping the merge goal ***
      - name: Build, Test, and Verify with Maven
        run: mvn -B verify

      # Optional but helpful diagnostic step if things break later
      - name: Check for jacoco.exec files AFTER verify
        if: failure() # Only run if verify fails, to see what might be missing
        run: |
          echo "--- Checking for jacoco.exec files ---"
          find . -path '*/target/jacoco.exec' -ls
          echo "--- Finished checking ---"

      - name: Upload Unit Test Results (Surefire)
        if: always() # Upload test results even if build fails
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/target/surefire-reports/*.xml'
          retention-days: 7

      - name: Upload Code Coverage Report (Jacoco Aggregate)
        if: success() # Only upload coverage if build succeeds
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-code-coverage-report
          path: shodrone-util-ci/target/site/jacoco-aggregate/
          retention-days: 7