name: Java CI with Maven (Debug JaCoCo Merge)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test Java Components

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # Run verify, but activate the profile to SKIP the merge goal
      - name: Build, Test, and Verify with Maven (Skip JaCoCo Merge)
        run: mvn -B verify -PskipJaCoCoMerge

      # ---- More Detailed Diagnostic Step ----
      - name: Check for jacoco.exec files AFTER verify
        if: always() # Run even if verify failed
        run: |
          echo "--- Checking for jacoco.exec files ---"
          # Use find with -ls to show details including timestamp and size
          find . -path '*/target/jacoco.exec' -ls
          echo "--- If no files are listed above, no jacoco.exec was generated! ---"
          echo "--- Checking target directories existence ---"
          ls -ld */target shodrone-backoffice/*/target # List target dirs
          echo "--- Finished checking ---"
      # ---- END DIAGNOSTIC STEP ----

      - name: Upload Unit Test Results (Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/target/surefire-reports/*.xml'
          retention-days: 7

      - name: Upload Code Coverage Report (Jacoco Aggregate)
        # report-aggregate should still work even if merge was skipped
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-aggregate-report
          path: shodrone-util-ci/target/site/jacoco-aggregate/
          retention-days: 7